// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNML0DdKZYlPx6DjGDKjKYcw0jxAK_U1A',
    appId: '1:706359539727:web:9fb9e29a3c361155f40b7a',
    messagingSenderId: '706359539727',
    projectId: 'aahar-f50b3',
    authDomain: 'aahar-f50b3.firebaseapp.com',
    storageBucket: 'aahar-f50b3.firebasestorage.app',
    measurementId: 'G-G428SQS496',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJIBgs3mAfxbLAU9kLH-C2NbPv4aZV8hM',
    appId: '1:706359539727:android:1e34b4ef2e368e27f40b7a',
    messagingSenderId: '706359539727',
    projectId: 'aahar-f50b3',
    storageBucket: 'aahar-f50b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi1C0-FcNZS6F7pM-XrUGJytYKrmEau-o',
    appId: '1:706359539727:ios:6745a6390e39ecaff40b7a',
    messagingSenderId: '706359539727',
    projectId: 'aahar-f50b3',
    storageBucket: 'aahar-f50b3.firebasestorage.app',
    iosBundleId: 'com.example.solutionChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi1C0-FcNZS6F7pM-XrUGJytYKrmEau-o',
    appId: '1:706359539727:ios:6745a6390e39ecaff40b7a',
    messagingSenderId: '706359539727',
    projectId: 'aahar-f50b3',
    storageBucket: 'aahar-f50b3.firebasestorage.app',
    iosBundleId: 'com.example.solutionChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNML0DdKZYlPx6DjGDKjKYcw0jxAK_U1A',
    appId: '1:706359539727:web:60dd8c5b7929a086f40b7a',
    messagingSenderId: '706359539727',
    projectId: 'aahar-f50b3',
    authDomain: 'aahar-f50b3.firebaseapp.com',
    storageBucket: 'aahar-f50b3.firebasestorage.app',
    measurementId: 'G-ZHV34C1W3E',
  );
}